FROM postgres:latest

MAINTAINER zombie(zombiesoul@163.com)

ENV TZ=Asia/Shanghai

RUN ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY sql/postres/01schema.sql /docker-entrypoint-initdb.d

COPY sql/postres/02worker-samples.sql /docker-entrypoint-initdb.d
